/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.harman;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import com.harman.hkwirelessapi.AudioCodecHandler;

// This proxy can be created by calling Harman.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = HarmanModule.class)
public class AudioCodecHandlerProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "ExampleProxy";
	AudioCodecHandler hAudioControl;

	// Constructor
	public AudioCodecHandlerProxy() {
		super();
		hAudioControl = new AudioCodecHandler();
	}

	@Kroll.method
	public void playWAV(KrollDict opts) {
		hAudioControl.playWAV("");
	}

	@Kroll.method
	public void playStreamingMedia(KrollDict opts) {
		hAudioControl.playStreamingMedia("URL");
	}

	@Kroll.method
	public void playCAV(KrollDict opts) {
		hAudioControl.playCAF("", "", true);
	}
}